### ISSUE TITLE
Book's code examples doesn't match those from the repo

### ISSUE THREAD

**Issue by eda1-fiunam** [johnttaylor/pim#1]
Either the book or the repo is useless as far as they don't match. In pages 47..52 you give an examples of NV memory, and in page 52 (Fig. 4-4) you show a file tree in which one can see some examples using discrete chips like the 24AA160 or the M95160DRE eeproms. Although they are printed out in the book, they don't exist in the repo! Not even as mocks. I couldn't even find the SPI interface: src/Driver/SPI/Interface.h.

You made a big mistake in forgetting to create a static repo that matches the book's code (in case your code got bigger). Even worst if you use a code base for the book and other code base for the repo.

**Comment by johnttaylor** [comment]
The Persistent storage example discussed in Chapter 3 and the first part of Chapter 4 is a hypothetical-example for illustrative purposes only, hence no source code in the PIM repository.  The second part of Chapter 4 (starting on page 53) goes into detail of the Persistent Storage sub-system that is implemented PIM repository

**Comment by eda1-fiunam** [comment]
The philosophy behind your book is great, and the book is full of good advices. However your PIM project is so big that it can hardly be used as an example. It's like an author of a medium size book on Linux tells you "... well, for details you can take a look at the Linux's repo"!

Things get worst if the book is full of hypothetical examples one can't follow :(

**Comment by johnttaylor** [comment]
Thanks for the feedback - even the 'ugly bits'.  I will keep your suggestions in mind if/when there are follow-up to the book.
