### ISSUE TITLE
logging?

### ISSUE THREAD

**Issue by peterus** [johnttaylor/pim#16]
I was trying to get some Idea if you do some regular logging, but I could not finde something.
What is your idea with logging? I understand that you have some kind of CLI to check model points. but what If you want to print some data/text/values in a regular basis. Or the progress of your FW while startup/running.

**Comment by johnttaylor** [comment]
The answer is not currently.  I updated your issue request in Github with
more details.

-john

**Comment by johnttaylor** [comment]
FYI - the PIM repo has been update with the Cpl logging framework.  However there is still no 'backend' for persisting the log entries.
