### ISSUE TITLE
Hidden Overloaded Virtual Function Warnings

### ISSUE THREAD

**Issue by phillipjohnston** [johnttaylor/pim#3]
I know that you call for using GCC on Linux, but I am currently compiling the project with Clang on OS X out of convenience. There are noteworthy warnings being reported by my compiler related to hidden overloaded virtual functions. I've attached the make.log with the warnings for your reference.

[make.log](https://github.com/johnttaylor/pim/files/9065533/make.log)

**Comment by johnttaylor** [comment]
Thank you for the feedback - obviously I don't see these warnings using the GCC compiler.  The warnings all come from the  `Cpl::Dm::Mp` namespace.  I refactored the `Cpl::Dm` and `Cpl::Dm::Mp` namespace last month to have a small program-space footprint as well as simpler to add new/custom model point types.  Can you please pull the latest code from the master branch and see if these warning are present?

Note: The original source was published when PIM was publish is readily available on the `original-book-release` branch

**Comment by phillipjohnston** [comment]
There are still hidden overloaded virtual function warnings as of commit 9faf16725d4c682d91f4f41a83e69ef3fbe67ce3. [Log attached](https://github.com/johnttaylor/pim/files/9073011/make.log) for reference.

Briefly looked into this, some notes below. I'm using `Cpl::Dm::ModelPointCommon_::write` and derived `write` implementations for context.

There is only a problem if someone is intended to invoke the non-type-safe write interface on a type-specific model point. The compiler won't search base classes for a matching function name/signature since one with the same name is provided by the derived class.

Possible resolutions:

- If you want someone to be able to invoke the base class `write`, then in the `protected` section in the shadowing classes, you can add `using Cpl::Dm::ModelPointCommon_::write;`
- If you don't want someone to be able to invoke the base class `write`, then you could put `using Cpl::Dm::ModelPointCommon_::write;` in the private section
- Class hierarchy redesign
     - It appears that the two-parameter write is only overridden in the `ModelPointCommon_` class, which is then used by derived classes to implement their write method. In this case, the write method in `ModelPointCommon_` class does not technically need to be `virtual`. Making it non-`virtual` would then avoid the shadowing as well. This would also require a consideration as to whether the two-parameter write is actually part of the base class abstract interface - again, I think that is ultimately a question of whether or not it is used in the program through that abstract interface.
- Let the warning go, disable it on Clang when build lands

**Comment by johnttaylor** [comment]
The CPP Faq link help a lot on why this warning exists.  In the context of the Model Point code - the hidden functions are all protected scope and the argument differences are sufficient that if/when a developer is creating a new model point they won't be calling the wrong virtual function (they may not understand why the compile won't resolve their call to the base class's method - BTW in hindsight I had exactly this problem that I resolved by fully qualify the function call with the base class's name).  All that said - I will fix the warnings by adding the `using` statements to the derived classes.

**Comment by johnttaylor** [comment]
This has been resolved in commit [22c1e68](https://github.com/johnttaylor/pim/commit/22c1e68c8045d3fd5dad0f1ee023ec5d0abc67eb)
